### ISSUE TITLE
nächtliche Berechnung IOException: Could not fetch URL

### ISSUE THREAD

**Issue by stefanhoth** [immopoly/immopoly#19]
@mrschtief:

Mit darauffolgender NPE in CronjobServlet.java:63

Abfangen und diesen Request ignorieren

2011-07-27 00:08:04.209
org.immopoly.appengine.WebHelper getHttpData: request failed
java.io.IOException: Could not fetch URL: http://rest.immobilienscout24.de/restapi/api/search/v1.0/expose/61417476.json
at com.google.appengine.api.urlfetch.URLFetchServiceImpl.convertApplicationException(URLFetchServiceImpl.java:115)
at com.google.appengine.api.urlfetch.URLFetchServiceImpl.fetch(URLFetchServiceImpl.java:42)
at com.google.apphosting.utils.security.urlfetch.URLFetchServiceStreamHandler$Connection.fetchResponse(URLFetchServiceStreamHandler.java:418)
at com.google.apphosting.utils.security.urlfetch.URLFetchServiceStreamHandler$Connection.getInputStream(URLFetchServiceStreamHandler.java:297)
at org.immopoly.appengine.WebHelper.getHttpData(WebHelper.java:29)
at org.immopoly.appengine.CronjobServlet.doGet(CronjobServlet.java:62)

**Comment by stefanhoth** [comment]
duplicate
