### ISSUE TITLE
IOException: Could not fetch URL: http://rest.immobilienscout24.de/restapi/api/search/v1.0/expose/

### ISSUE THREAD

**Issue by stefanhoth** [immopoly/immopoly#22]
@mrschtief:

Wir haben ein neues Problem am 28.7.2011 sind die nächtlichen Berechnungen zwischen 00:04 und 00:49 Uhr nicht ausgeführt worden. Die IS24 REST-API konnten aufgrund folgender Exception nicht durchgeführt werden:

Ich vermute Serverausfall bei IS24

java.io.IOException: Could not fetch URL: http://rest.immobilienscout24.de/restapi/api/search/v1.0/expose/61177002.json
at com.google.appengine.api.urlfetch.URLFetchServiceImpl.convertApplicationException(URLFetchServiceImpl.java:115)
at com.google.appengine.api.urlfetch.URLFetchServiceImpl.fetch(URLFetchServiceImpl.java:42)
at com.google.apphosting.utils.security.urlfetch.URLFetchServiceStreamHandler$Connection.fetchResponse(URLFetchServiceStreamHandler.java:418)
at com.google.apphosting.utils.security.urlfetch.URLFetchServiceStreamHandler$Connection.getInputStream(URLFetchServiceStreamHandler.java:297)
at org.immopoly.appengine.WebHelper.getHttpData(WebHelper.java:29)
at org.immopoly.appengine.CronjobServlet.doGet(CronjobServlet.java:62)

Mehr infos zum URLFetchService

http://code.google.com/intl/de-DE/appengine/docs/java/javadoc/com/google/appengine/api/urlfetch/URLFetchService.html

Hier ein paar expose-Ids für die kein Request durchgeführt werden konnte:
00:20Uhr 61177002 failed 
00:19Uhr 59005879 failed
00:18Uhr 60510104 failed

**Comment by stefanhoth** [comment]
@mrschtief:

Vielleicht schlägt hier die 10s Deadline zu siehe:

http://code.google.com/intl/de-DE/appengine/docs/java/urlfetch/overview.html#Quotas_and_Limits

**Comment by stefanhoth** [comment]
@rob-bors

Ursache ist gefunden: wir hatten einen Releasewechsel mit einer Downtime. 
Ich habe das nicht vorab bekanntgegeben, weil es keinen API-Anwender gibt, der nachts Traffic hat Und wie konnte ich euch dabei vergessen!

Sorry,

Rob
Produktmanager APIs
ImmobilienScout24

**Comment by stefanhoth** [comment]
@mrschtief:

OK danke für den Report.

Ich fixe noch die folgende NPE

java.lang.NullPointerException
at org.immopoly.appengine.CronjobServlet.doGet(CronjobServlet.java:63)

**Comment by stefanhoth** [comment]
@mrschtief: fixed und deployed
